name: LateX to PDF

on:
  push:
    branches: 
      - main
    tags:
       - '*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    outputs: 
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }} 

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 #fetch-depth is needed for GitVersion
        
      # Install and calculate the new version with GitVersion  
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: 5.x
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        id: gitversion # step id used as reference for output values
      - name: Display GitVersion outputs
        run: |
          echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
          echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
        
      - name: latex2pdf
        id: compile-latex-document
        uses: thomas-chauvet/latex2pdf-action@1.1.0
        with:
          output_dir: build
          main_latex_file: abel-resume.tex
          ctan_packages: fira parskip

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: build/abel-resume.pdf
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest    
    needs: build_latex
    if: github.ref == 'refs/heads/main' # only run job if on the main branch   
    
    steps:  
      - name: Download PDF artifact
        uses: actions/download-artifact@v1
        with:
          name: resume

      - name: Get the latest release number
        id: get_latest_release
        run: |
          latest_release=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.name')
          if [[ $latest_release =~ Release\ ([0-9]+) ]]; then
            release_number=${BASH_REMATCH[1]}
            next_release_number=$((release_number + 1))
          else
            next_release_number=1
          fi
          echo "::set-output name=next_release_number::$next_release_number"

      # Create a release
      - name: Create Release
        if: needs.build_latex.outputs.CommitsSinceVersionSource > 0 #Only release if there has been a commit/version change
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.build_latex.outputs.Version }}
          name: Release ${{ steps.get_latest_release.outputs.next_release_number }}
          artifacts: "resume/*"
          token: ${{ secrets.RELEASE_PUBLISH_TOKEN }}
